services:
  - type: web
    name: creative-prompt-writing
    env: node
    plan: starter
    region: singapore
    # Update the following line with your Strapi GitHub repo
    repo: https://github.com/OpenPecha/creative-prompt-writing.git
    branch: main
    buildCommand: npm ci --production=false && npm run build && npm prune --production
    startCommand: npx prisma migrate deploy && npm run start
    envVars:
      - key: NODE_VERSION
        value: ~18.18.0
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: creative-prompt-writing-pg
          property: connectionString

databases:
  - name: creative-prompt-writing-pg
    plan: starter
    region: singapore
